# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: gen-password 0.16.0 ruby lib

Gem::Specification.new do |s|
  s.name = "gen-password"
  s.version = "0.16.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Albert Lash", "Ian Macdonald", "Akshay Mankar", "Vini Gupta"]
  s.date = "2014-01-13"
  s.description = "Ruby/GenPassword is a suite of password handling methods for Ruby. It supports\nthe manual entry of passwords from the keyboard in both buffered and\nunbuffered modes, random password generation,\nphonemic password generation (for easy memorisation by human-beings) and the\nencryption of passwords. It is a fork of Ruby/Password without password checking using cracklib"
  s.email = "itsakshaymankar@gmail.com"
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "CHANGES",
    "COPYING",
    "Changelog",
    "README",
    "Rakefile",
    "VERSION",
    "example/crypt.rb",
    "example/example.rb",
    "example/pw.rb",
    "example/pwgen",
    "lib/password.rb",
    "test/tc_password.rb"
  ]
  s.homepage = "http://www.docunext.com/"
  s.require_paths = ["lib"]
  s.rubygems_version = "2.1.11"
  s.summary = "A password handling library for Ruby"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ruby-termios>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
    else
      s.add_dependency(%q<ruby-termios>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<ruby-termios>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
  end
end

